apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-server
  labels:
    app.kubernetes.io/name: {{ include "distributed-jmeter.name" . }}
    helm.sh/chart: {{ include "distributed-jmeter.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    role: server
spec:
  replicas: {{ .Values.server.replicaCount }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "distributed-jmeter.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      role: server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "distributed-jmeter.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        role: server
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["server"]
          ports:
            - containerPort: 50000
            - containerPort: 1099
          volumeMounts:
            - name: user-properties
              mountPath: /jmeter/bin/user.properties
              readOnly: true
              subPath: "user.properties"
            - name: data
              mountPath: /jmeter/data
              subPath: "data"
      volumes:
        - name:  user-properties
          configMap:
            name: {{ .Release.Name }}-user-properties
        - name: data
          {{- if .Values.dataVolume.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-data
          {{ else }}
          emptyDir: {}
          {{ end }}